package com.srvn;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;

import javax.swing.*;
import javax.sound.sampled.*;

public class FrameMusicPlayer extends javax.swing.JFrame {
    //TODO : terminar barra de progreso, 
    //TODO : al terminar cancion reproducir siguiente automaticamente
    //TODO : poner controlador de sonido (mute)
    //TODO : poner imagen de portada
    //TODO : poner el nombre de la cancion debajo del nombre

    private File[] playList;

    private Integer playPosition = null;

    private Clip clip;

    private DefaultListModel<String> modelo = new DefaultListModel<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMusicPlayer.class.getName());

    /**
     * Creates new form FrameMusicPlayer
     */
    public FrameMusicPlayer() {
        initComponents();

        String userHome = System.getProperty("user.home");
        File musicFolder = new File(userHome, "Music"); // En inglés (Windows)
        if (!musicFolder.exists()) {
            musicFolder = new File(userHome, "Música"); // En español
        }
        System.out.print(musicFolder.getPath());

        loadPlayList(musicFolder.getAbsolutePath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPricipal = new javax.swing.JPanel();
        panelSub = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myListMusic = new javax.swing.JList<>();
        prgressBar = new javax.swing.JProgressBar();
        panelControls = new javax.swing.JPanel();
        buttonPlay = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonPrev = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonLadFolder = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPricipal.setBackground(new java.awt.Color(136, 206, 250));

        panelSub.setBackground(new java.awt.Color(177, 225, 255));

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));

        myListMusic.setModel(modelo);
        myListMusic.addListSelectionListener(this::myListMusicValueChanged);
        jScrollPane1.setViewportView(myListMusic);

        prgressBar.setStringPainted(true);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(prgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelControls.setBackground(new java.awt.Color(255, 255, 255));

        buttonPlay.setBackground(new java.awt.Color(218, 241, 255));
        buttonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/boton-play.png"))); // NOI18N
        buttonPlay.addActionListener(this::buttonPlayActionPerformed);

        buttonStop.setBackground(new java.awt.Color(218, 241, 255));
        buttonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/detener.png"))); // NOI18N
        buttonStop.addActionListener(this::buttonStopActionPerformed);

        buttonNext.setBackground(new java.awt.Color(218, 241, 255));
        buttonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/boton-de-salto.png"))); // NOI18N
        buttonNext.addActionListener(this::buttonNextActionPerformed);

        buttonPrev.setBackground(new java.awt.Color(218, 241, 255));
        buttonPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/boton-de-rebobinado (1).png"))); // NOI18N
        buttonPrev.addActionListener(this::buttonPrevActionPerformed);

        jButton1.setBackground(new java.awt.Color(218, 241, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/loop.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        buttonLadFolder.setBackground(new java.awt.Color(218, 241, 255));
        buttonLadFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/upload.png"))); // NOI18N
        buttonLadFolder.addActionListener(this::buttonLadFolderActionPerformed);

        javax.swing.GroupLayout panelControlsLayout = new javax.swing.GroupLayout(panelControls);
        panelControls.setLayout(panelControlsLayout);
        panelControlsLayout.setHorizontalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLadFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelControlsLayout.setVerticalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonLadFolder)
                    .addComponent(jButton1)
                    .addComponent(buttonNext)
                    .addComponent(buttonStop)
                    .addComponent(buttonPlay)
                    .addComponent(buttonPrev))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSubLayout = new javax.swing.GroupLayout(panelSub);
        panelSub.setLayout(panelSubLayout);
        panelSubLayout.setHorizontalGroup(
            panelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubLayout.setVerticalGroup(
            panelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPricipalLayout = new javax.swing.GroupLayout(panelPricipal);
        panelPricipal.setLayout(panelPricipalLayout);
        panelPricipalLayout.setHorizontalGroup(
            panelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPricipalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panelSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelPricipalLayout.setVerticalGroup(
            panelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPricipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void myListMusicValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_myListMusicValueChanged

        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (playList == null) {
            return;
        }

        int index = myListMusic.getSelectedIndex();

        if (index >= 0) {

            playPosition = index;

            reproducirArchivo(playList[playPosition]);
        }
    }//GEN-LAST:event_myListMusicValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonLadFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLadFolderActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File folder = fileChooser.getSelectedFile();

        if (folder == null) {
            return;
        }

        playPosition = null;

        if (clip != null) {
            clip.stop();
            clip.close();
        }

        loadPlayList(folder.getAbsolutePath());
    }//GEN-LAST:event_buttonLadFolderActionPerformed

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevActionPerformed
        // ❌ Negator
        if (playList == null || playList.length == 0) {
            return;
        }

        int index = myListMusic.getSelectedIndex();

        // ❌ Si no hay selección → empezar en 0
        if (index < 0) {
            index = 0;
        } else {
            index--;
        }

        // 🔁 Si baja de 0 → ir al último
        if (index < 0) {
            index = playList.length - 1;
        }

        // ✔ actualizar estado
        playPosition = index;
        myListMusic.setSelectedIndex(index);

    }//GEN-LAST:event_buttonPrevActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        if (playList == null || playList.length == 0) {
            return;
        }

        int index = myListMusic.getSelectedIndex();

        // ❌ Si no hay selección → empezar en 0
        if (index < 0) {
            index = 0;
        } else {
            index++;
        }

        // 🔁 Si llega al final → volver al inicio
        if (index >= playList.length) {
            index = 0;
        }

        // ✔ actualizar estado
        playPosition = index;
        myListMusic.setSelectedIndex(index);
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed

        if (clip != null) {
            clip.stop();
            clip.close();
        }
        playPosition = null;
    }//GEN-LAST:event_buttonStopActionPerformed

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        // ❌ Negator
        if (playList == null || playList.length == 0) {
            JOptionPane.showMessageDialog(this, "No hay canciones en la lista");
            return;
        }

        int index = myListMusic.getSelectedIndex();

        // ❌ Si no hay selección → seleccionar el primero
        if (index < 0) {
            index = 0;
            myListMusic.setSelectedIndex(index); // 🔥 esto dispara el evento y reproduce
            return;
        }

        // ✔ Si ya hay selección
        playPosition = index;
    }//GEN-LAST:event_buttonPlayActionPerformed

    public void reproducirArchivo(File archivo) {

        try {
            if (clip != null && clip.isRunning()) {
                clip.stop();
                clip.close();
            }
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(archivo);

            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();

            JOptionPane.showMessageDialog(
                    this,
                    "Reproduciendo: " + archivo.getName()
            );
        } catch (UnsupportedAudioFileException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "El archivo no es un WAV válido."
            );

        } catch (LineUnavailableException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay línea de audio disponible."
            );

        } catch (HeadlessException | IOException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al reproducir el archivo."
            );

            ex.printStackTrace();
        }

    }

    public void loadPlayList(String path) {

        File folder = new File(path);

        // ❌ Negator: validar primero lo inválido
        if (!folder.exists() || !folder.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Ruta inválida");
            return;
        }

        File[] listaArchivos = folder.listFiles();

        // ❌ Negator: evitar null
        if (listaArchivos == null) {
            JOptionPane.showMessageDialog(this, "No se pudo leer la carpeta");
            return;
        }

        modelo.clear();

        java.util.List<File> listaWav = new java.util.ArrayList<>();

        for (File archivo : listaArchivos) {

            // ❌ Negator: ignorar lo que no sirve
            if (!archivo.isFile() || !archivo.getName().toLowerCase().endsWith(".wav")) {
                continue;
            }

            listaWav.add(archivo);
            modelo.addElement(archivo.getName());
        }

        // ✔ conversión moderna
        playList = listaWav.toArray(File[]::new);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameMusicPlayer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLadFolder;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonPrev;
    private javax.swing.JButton buttonStop;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> myListMusic;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelControls;
    private javax.swing.JPanel panelPricipal;
    private javax.swing.JPanel panelSub;
    private javax.swing.JProgressBar prgressBar;
    // End of variables declaration//GEN-END:variables
}
