package com.srvn;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;

import javax.swing.*;
import javax.sound.sampled.*;

public class FrameMusicPlayer extends javax.swing.JFrame {

    private File[] playList;

    private Integer playPosition = null;

    private Clip clip;

    private DefaultListModel<String> modelo = new DefaultListModel<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMusicPlayer.class.getName());

    /**
     * Creates new form FrameMusicPlayer
     */
    public FrameMusicPlayer() {
        initComponents();

        String userHome = System.getProperty("user.home");
        File musicFolder = new File(userHome, "Music"); // En inglés (Windows)
        if (!musicFolder.exists()) {
            musicFolder = new File(userHome, "Música"); // En español
        }
        System.out.print(musicFolder.getPath());

        loadPlayList(musicFolder.getAbsolutePath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myListMusic = new javax.swing.JList<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        buttonLadFolder = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonPlay = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myListMusic.setModel(modelo);
        myListMusic.addListSelectionListener(this::myListMusicValueChanged);
        jScrollPane1.setViewportView(myListMusic);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        buttonLadFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/upload.png"))); // NOI18N
        buttonLadFolder.addActionListener(this::buttonLadFolderActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(buttonLadFolder)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(buttonLadFolder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/boton-play.png"))); // NOI18N
        buttonPlay.addActionListener(this::buttonPlayActionPerformed);

        buttonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/detener.png"))); // NOI18N
        buttonStop.addActionListener(this::buttonStopActionPerformed);

        buttonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/boton-de-salto.png"))); // NOI18N
        buttonNext.addActionListener(this::buttonNextActionPerformed);

        buttonPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/srvn/assets/boton-de-rebobinado (1).png"))); // NOI18N
        buttonPrev.addActionListener(this::buttonPrevActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(buttonPrev)
                .addGap(18, 18, 18)
                .addComponent(buttonStop)
                .addGap(18, 18, 18)
                .addComponent(buttonPlay)
                .addGap(18, 18, 18)
                .addComponent(buttonNext))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonPrev)
                    .addComponent(buttonNext)
                    .addComponent(buttonPlay)
                    .addComponent(buttonStop))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(178, 178, 178))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        // ❌ Negator
        if (playList == null || playList.length == 0) {
            JOptionPane.showMessageDialog(this, "No hay canciones en la lista");
            return;
        }

        int index = myListMusic.getSelectedIndex();

        // ❌ Si no hay selección → seleccionar el primero
        if (index < 0) {
            index = 0;
            myListMusic.setSelectedIndex(index); // 🔥 esto dispara el evento y reproduce
            return;
        }

        // ✔ Si ya hay selección
        playPosition = index;
        reproducirArchivo(playList[index]);    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonLadFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLadFolderActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File folder = fileChooser.getSelectedFile();

        if (folder == null) {
            return;
        }

        playPosition = null;

        if (clip != null) {
            clip.stop();
            clip.close();
        }

        loadPlayList(folder.getAbsolutePath());
    }//GEN-LAST:event_buttonLadFolderActionPerformed


    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed

        if (clip != null) {
            clip.stop();
            clip.close();
        }
        playPosition = null;

    }//GEN-LAST:event_buttonStopActionPerformed

    private void myListMusicValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_myListMusicValueChanged

        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (playList == null) {
            return;
        }

        int index = myListMusic.getSelectedIndex();

        if (index >= 0) {

            playPosition = index;

            reproducirArchivo(playList[playPosition]);
        }
    }//GEN-LAST:event_myListMusicValueChanged

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        if (playList == null || playList.length == 0) {
            return;
        }

        int index = myListMusic.getSelectedIndex();

        // ❌ Si no hay selección → empezar en 0
        if (index < 0) {
            index = 0;
        } else {
            index++;
        }

        // 🔁 Si llega al final → volver al inicio
        if (index >= playList.length) {
            index = 0;
        }

        // ✔ actualizar estado
        playPosition = index;
        myListMusic.setSelectedIndex(index);

    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevActionPerformed
        // ❌ Negator
        if (playList == null || playList.length == 0) {
            return;
        }

        int index = myListMusic.getSelectedIndex();

        // ❌ Si no hay selección → empezar en 0
        if (index < 0) {
            index = 0;
        } else {
            index--;
        }

        // 🔁 Si baja de 0 → ir al último
        if (index < 0) {
            index = playList.length - 1;
        }

        // ✔ actualizar estado
        playPosition = index;
        myListMusic.setSelectedIndex(index);


    }//GEN-LAST:event_buttonPrevActionPerformed

    public void reproducirArchivo(File archivo) {

        try {
            if (clip != null && clip.isRunning()) {
                clip.stop();
                clip.close();
            }
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(archivo);

            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();

            JOptionPane.showMessageDialog(
                    this,
                    "Reproduciendo: " + archivo.getName()
            );
        } catch (UnsupportedAudioFileException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "El archivo no es un WAV válido."
            );

        } catch (LineUnavailableException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay línea de audio disponible."
            );

        } catch (HeadlessException | IOException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al reproducir el archivo."
            );

            ex.printStackTrace();
        }

    }

    public void loadPlayList(String path) {

        File folder = new File(path);

        // ❌ Negator: validar primero lo inválido
        if (!folder.exists() || !folder.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Ruta inválida");
            return;
        }

        File[] listaArchivos = folder.listFiles();

        // ❌ Negator: evitar null
        if (listaArchivos == null) {
            JOptionPane.showMessageDialog(this, "No se pudo leer la carpeta");
            return;
        }

        modelo.clear();

        java.util.List<File> listaWav = new java.util.ArrayList<>();

        for (File archivo : listaArchivos) {

            // ❌ Negator: ignorar lo que no sirve
            if (!archivo.isFile() || !archivo.getName().toLowerCase().endsWith(".wav")) {
                continue;
            }

            listaWav.add(archivo);
            modelo.addElement(archivo.getName());
        }

        // ✔ conversión moderna
        playList = listaWav.toArray(File[]::new);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameMusicPlayer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLadFolder;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonPrev;
    private javax.swing.JButton buttonStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> myListMusic;
    // End of variables declaration//GEN-END:variables
}
